#!/usr/bin/env python3
"""Generate database install scripts that embed src/sqljev/core.py (one stdlib-only module).

    python scripts/build_sql.py            # rewrite the generated files
    python scripts/build_sql.py --check    # CI: fail when a generated file is stale
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CORE = (ROOT / "src/sqljev/core.py").read_text()

SNOWFLAKE = '''-- GENERATED by scripts/build_sql.py from src/sqljev/core.py — edit those, not this file.
--
-- sql-jev-laya for Snowflake, as a vectorized Python UDF. Snowflake hands the UDF batches of rows; each batch is
-- de-duplicated, looked up in the cache and sent to the model in large requests.
--
--   SELECT * FROM tickets t WHERE jev(OBJECT_CONSTRUCT(t.*), 'the customer is angry');
--   SELECT jev_choice(OBJECT_CONSTRUCT(t.*), 'which team should handle this?',
--                     ['billing', 'technical', 'sales']) AS team, COUNT(*) FROM tickets t GROUP BY 1;
--
-- The UDF calls out over HTTPS, so it needs an External Access Integration. Point it at:
--   * a sql-jev-laya gateway running Laya (recommended: your own GPU box / container, data stays in your cloud), or
--   * TypeSafe Jev (backend 'jev').
-- To keep rows inside Snowflake entirely, run Laya in Snowpark Container Services: see install_spcs.sql.
--
-- 1. Edit the three values marked EDIT below, then run this script as a role that can create integrations.

USE ROLE ACCOUNTADMIN;                                    -- or a role with CREATE INTEGRATION
CREATE DATABASE IF NOT EXISTS SQLJEV;
CREATE SCHEMA IF NOT EXISTS SQLJEV.PUBLIC;
USE SCHEMA SQLJEV.PUBLIC;

CREATE OR REPLACE NETWORK RULE sqljev_egress
  MODE = EGRESS TYPE = HOST_PORT
  VALUE_LIST = ('gateway.example.com:443');                -- EDIT: your gateway host (or api.typesafe.ai:443)

CREATE OR REPLACE SECRET sqljev_token
  TYPE = GENERIC_STRING
  SECRET_STRING = 'replace-me';                            -- EDIT: SQLJEV_GATEWAY_TOKEN (or TypeSafe API key)

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION sqljev_access
  ALLOWED_NETWORK_RULES = (sqljev_egress)
  ALLOWED_AUTHENTICATION_SECRETS = (sqljev_token)
  ENABLED = TRUE;

CREATE OR REPLACE FUNCTION jev_eval(row VARIANT, question STRING, kind STRING, options ARRAY)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('pandas')
HANDLER = 'sqljev_eval_batch'
EXTERNAL_ACCESS_INTEGRATIONS = (sqljev_access)
SECRETS = ('token' = sqljev_token)
AS $$
# ---------------- sqljev.core (inlined) ----------------
@@CORE@@
# ---------------- Snowflake handler ----------------
import _snowflake
import pandas
from _snowflake import vectorized

SQLJEV_SETTINGS = {"backend": "gateway", "api_url": "https://gateway.example.com/v1/eval"}   # EDIT

_engine = None


def _get_engine():
    global _engine
    if _engine is None:
        _engine = Jev(SQLJEV_SETTINGS, api_key=_snowflake.get_generic_secret_string("token"))
    return _engine


@vectorized(input=pandas.DataFrame, max_batch_size=2000)
def sqljev_eval_batch(df):
    calls = [(r[0], r[1], r[2] or "noul", r[3]) for r in df.itertuples(index=False, name=None)]
    return pandas.Series(_get_engine().call("jev_eval", calls))
$$;

CREATE OR REPLACE FUNCTION jev_prob(row VARIANT, condition STRING)
RETURNS FLOAT AS $$ jev_eval(row, condition, 'noul', NULL):noul::FLOAT $$;

CREATE OR REPLACE FUNCTION jev(row VARIANT, condition STRING)
RETURNS BOOLEAN AS $$ jev_prob(row, condition) >= 0.5 $$;

CREATE OR REPLACE FUNCTION jev(row VARIANT, condition STRING, threshold FLOAT)
RETURNS BOOLEAN AS $$ jev_prob(row, condition) >= threshold $$;

CREATE OR REPLACE FUNCTION jev_score(row VARIANT, question STRING, levels ARRAY)
RETURNS FLOAT AS $$ jev_eval(row, question, 'score', levels):score::FLOAT $$;

CREATE OR REPLACE FUNCTION jev_score_norm(row VARIANT, question STRING, levels ARRAY)
RETURNS FLOAT AS $$ jev_score(row, question, levels) / GREATEST(ARRAY_SIZE(levels) - 1, 1) $$;

CREATE OR REPLACE FUNCTION jev_choice(row VARIANT, question STRING, options ARRAY)
RETURNS STRING AS $$ jev_eval(row, question, 'choice', options):choice::STRING $$;

CREATE OR REPLACE FUNCTION jev_confidence(row VARIANT, question STRING, kind STRING, options ARRAY)
RETURNS FLOAT AS $$ jev_eval(row, question, kind, options):confidence::FLOAT $$;
'''


def render():
    core = CORE.replace("$$", "$ $")     # never close the $$ body early
    assert "@@CORE@@" not in core
    return {ROOT / "sql/snowflake/install_udf.sql": SNOWFLAKE.replace("@@CORE@@", core.rstrip())}


def main():
    stale = []
    for path, text in render().items():
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
            print("wrote", path.relative_to(ROOT))
    if stale:
        sys.exit("stale generated files (run python scripts/build_sql.py): " + ", ".join(stale))


if __name__ == "__main__":
    main()
